const styles = (isHovered) => ({
  card: {
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    maxWidth: '350px',
    backgroundColor: '#fff',
    fontFamily: 'Arial, sans-serif',
  },
  imageContainer: {
    height: '220px',
    position: 'relative',
    overflow: 'hidden',
  },
  image: { width: '100%', height: '100%', objectFit: 'cover' },
  badgeContainer: {
    position: 'absolute',
    top: '10px',
    left: '10px',
    display: 'flex',
    gap: '8px',
    zIndex: 10,
  },
  truCheck: {
    backgroundColor: '#007bff',
    color: 'white',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '0.75em',
    fontWeight: '600',
  },
  offPlan: {
    backgroundColor: '#ffc107',
    color: '#333',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '0.75em',
    fontWeight: '600',
  },
  handoverBadge: {
    position: 'absolute',
    bottom: '0',
    left: '0',
    backgroundColor: '#387373',
    color: 'white',
    padding: '8px 12px',
    fontSize: '0.85em',
    fontWeight: '600',
    borderTopRightRadius: '8px',
  },
  details: { padding: '15px' },
  price: {
    fontSize: '1.6em',
    fontWeight: '700',
    color: '#004c7d',
    marginBottom: '10px',
  },
  featuresWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
    fontSize: '1em',
    color: '#555',
    marginBottom: '15px',
    paddingBottom: '10px',
    borderBottom: '1px solid #f0f0f0',
  },
  shortDownloadBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '5px 10px',
    backgroundColor: isHovered ? '#003a61' : '#004c7d',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.8em',
    fontWeight: '600',
    marginLeft: 'auto',
    transition: '0.2s',
  },
  agentSection: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '15px',
    paddingTop: '15px',
    borderTop: '1px solid #eee',
  },
  agentImage: {
    width: '45px',
    height: '45px',
    borderRadius: '50%',
    marginRight: '12px',
    objectFit: 'cover',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
    backdropFilter: 'blur(8px)',
  },
  popup: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '16px',
    width: '350px',
    textAlign: 'center',
    boxShadow: '0 20px 40px rgba(0,0,0,0.3)',
  },
});

export default styles;
